import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

/**
 * GET /api/models
 * 
 * Returns available database models and their fields for field mapping.
 * Excludes auth-related models (Account, Session, VerificationToken, PasswordResetToken).
 */
export async function GET() {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json(
        { success: false, error: "Unauthorized" },
        { status: 401 }
      );
    }

    // Define available models for mapping (excluding auth models)
    const models = [
      {
        name: "CUSTORMER",
        displayName: "Customer",
        description: "Customer model for ERP integration",
        fields: [
          { name: "id", type: "Int", isId: true, isUnique: false, isRequired: true },
          { name: "SODTYPE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "TRDR", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "CODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "AFM", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "COUNTRY", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ADDRESS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ZIP", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "CITY", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PHONE01", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PHONE02", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "JOBTYPE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "WEBPAGE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "EMAIL", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "EMAILACC", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "IRSDATA", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INSDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "UPDDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "User",
        displayName: "User",
        description: "User model with profile information",
        fields: [
          { name: "id", type: "String", isId: true, isUnique: true, isRequired: true },
          { name: "email", type: "String", isId: false, isUnique: true, isRequired: true },
          { name: "password", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "role", type: "Role", isId: false, isUnique: false, isRequired: true },
          { name: "isActive", type: "Boolean", isId: false, isUnique: false, isRequired: true },
          { name: "emailVerified", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "image", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "firstName", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "lastName", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "address", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "zip", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "city", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "country", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "phone", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "mobile", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "workPhone", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "lastLoginAt", type: "DateTime", isId: false, isUnique: false, isRequired: false },
        ],
      },
      {
        name: "COUNTRY",
        displayName: "Country",
        description: "Country model for ERP integration",
        fields: [
          { name: "COUNTRY", type: "Int", isId: true, isUnique: false, isRequired: true },
          { name: "SHORTCUT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SOCURRENCY", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "INTCODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INTERCODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "IRSDATA",
        displayName: "IRS Data",
        description: "IRS Data model for ERP integration",
        fields: [
          { name: "IRSDATA", type: "String", isId: true, isUnique: false, isRequired: true },
          { name: "CODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ADDRESS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PHONE1", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ZIP", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "VAT",
        displayName: "VAT",
        description: "VAT model for ERP integration",
        fields: [
          { name: "VAT", type: "Int", isId: true, isUnique: false, isRequired: true },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PERCNT", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "VATS1", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "VATS3", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "MYDATACODE", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "DEPART", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "ACNMSKS", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "ACNMSKX", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "SOCURRENCY",
        displayName: "Currency",
        description: "Currency model for ERP integration",
        fields: [
          { name: "SOCURRENCY", type: "Int", isId: true, isUnique: false, isRequired: true },
          { name: "LOCKID", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "SHORTCUT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "INTERCODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "TRDCATEGORY",
        displayName: "Trade Category",
        description: "Trade Category model for ERP integration",
        fields: [
          { name: "TRDCATEGORY", type: "Int", isId: true, isUnique: false, isRequired: true },
          { name: "CODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ACNMSK", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "KEPYOST", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "COUNTRY", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "SOCURRENCY", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "COMPANY", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SODTYPE", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "ITEMS",
        displayName: "Items",
        description: "Items model for ERP integration",
        fields: [
          { name: "ITEMS", type: "Int", isId: true, isUnique: false, isRequired: true },
          { name: "COMPANY", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SODTYPE", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "MTRL", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "CODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "CODE1", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "CODE2", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "RELITEM", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "MTRTYPE1", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRACN", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRCATEGORY", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "VAT", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "MTRUNIT1", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRUNIT2", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRUNIT3", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRUNIT4", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MU21", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "MU31", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "MU41", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "MU12MODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MU13MODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MU14MODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRGROUP", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRMANFCTR", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "COUNTRY", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "MTRMARK", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRMODEL", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SOCURRENCY", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "INTRASTAT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "WEIGHT", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "WEBPAGE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "WEBNAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "WEBVIEW", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PRICEW", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "PRICER", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "DIM1", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "DIM2", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "DIM3", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "DIMMD", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "DIMMTRUNIT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SALQTY", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "PURQTY", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "ITEQTY", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "INSDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "UPDDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "GWEIGHT", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "MCOUNTRY", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "KADTAXIS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "cccSubgoup2", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "cccSubgroup3", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "PAYMENT",
        displayName: "Payment",
        description: "Payment method model for ERP integration",
        fields: [
          { name: "PAYMENT", type: "Int", isId: true, isUnique: true, isRequired: true },
          { name: "CODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "ACNMSK", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INSPAYMD", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INSCLCMD", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "CREDITCARDS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "VATPAYMENT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ISDOSE", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "PAYFROMDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "INSTALMENTS", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "MATURE", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "PAYROUND", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "MATURE1", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "EXPN", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SERIES", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "CHQTPRMS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "BANK", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "BANKBRANCH", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INTERESTDEB", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "INTERESTCRE", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "SODATA", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MYDATACODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "EFACTURACODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PAYACNMSK", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INSDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "UPDDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "INST",
        displayName: "Installation",
        description: "Installation model for ERP integration",
        fields: [
          { name: "INST", type: "Int", isId: true, isUnique: true, isRequired: true },
          { name: "CODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "NAME", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "ISACTIVE", type: "Int", isId: false, isUnique: false, isRequired: true },
          { name: "INSTTYPE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "TRDR", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "TRDBRANCH", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "BRANCH", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "BUSUNITS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SALESMAN", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "TRDRS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "TRDBRANCHS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "GPNT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PRSN", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "PRJC", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "FROMDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "BLOCKED", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "BLCKDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "GDATEFROM", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "GDATETO", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "WDATEFROM", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "WDATETO", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "INSDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "UPDDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "NUM01", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "REMARKS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
      {
        name: "INSTLINES",
        displayName: "Installation Lines",
        description: "Installation lines model for ERP integration (products/services for installations)",
        fields: [
          { name: "INSTLINES", type: "Int", isId: true, isUnique: true, isRequired: true },
          { name: "INST", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "LINENUM", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "SODTYPE", type: "Int", isId: false, isUnique: false, isRequired: false },
          { name: "MTRL", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "BUSUNITS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "QTY", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "PRICE", type: "Float", isId: false, isUnique: false, isRequired: false },
          { name: "FROMDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "FINALDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "COMMENTS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "SNCODE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INSTLINESS", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "MTRUNIT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "BAILTYPE", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "GPNT", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "TRDBRANCH", type: "String", isId: false, isUnique: false, isRequired: false },
          { name: "INSDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "UPDDATE", type: "DateTime", isId: false, isUnique: false, isRequired: false },
          { name: "createdAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
          { name: "updatedAt", type: "DateTime", isId: false, isUnique: false, isRequired: true },
        ],
      },
    ];

    return NextResponse.json({
      success: true,
      models,
    });
  } catch (error) {
    console.error("Get models error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to get models",
      },
      { status: 500 }
    );
  }
}








